# Nacos standalone mode with embedded database
server.contextPath=/nacos
server.servlet.contextPath=/nacos
server.port=8848
server.tomcat.accesslog.enabled=true

spring.sql.init.platform=embedded
nacos.core.auth.enabled=false
nacos.core.auth.system.type=nacos

# Embedded database
nacos.plugin.datasource.init.enabled=false
